### ISSUE TITLE
why do I only get 'xy', 'vega', and 'bullet"

### ISSUE THREAD

**Issue by curtislisle** [XDATA-Year-3/vcharts#38]
When I configure with bower, vcharts.js only picks up the above three templates, instead of all of the charts.  My checkout of recent commit is #8411e9cbe0b4a8b38bbae8fea031ad64df838ea5 (today, 11:41AM).  something I am doing wrong or is there a branch I should be on to try the others? It looked like relevant PR's were merged in before this commit.

**Comment by jeffbaumes** [comment]
I'll gladly cut another release for you :)

**Comment by jeffbaumes** [comment]
Now bower, npm, and website are updated with a 0.1.7 release.
